# Generated by Django 5.1.7 on 2025-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CALIDAD', 'Responsable de Control de Calidad'), ('MANTENIMIENTO', 'Responsable del Departamento de Mantenimiento')], max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
