# Generated by Django 5.1.7 on 2025-05-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
