# Generated by Django 5.1.7 on 2025-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='TAG de registro de equipos imel, siga el formato preestablecido en el link y edítelo cada vez que necesite renovar un TAG', verbose_name='Descripción')),
                ('direccion', models.URLField(help_text='Ingrese la URL del documento o recurso del TAG', verbose_name='Dirección de página')),
            ],
            options={
                'verbose_name': 'TAG de registro',
                'verbose_name_plural': 'TAG de registro',
            },
        ),
    ]
