# Generated by Django 5.1.7 on 2025-05-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('sector', models.CharField(choices=[('Laboratorio de Materias Primas', 'Laboratorio de Materias Primas'), ('Laboratorio de Producto Terminado', 'Laboratorio de Producto Terminado'), ('Laboratorio de Microbiología', 'Laboratorio de Microbiología'), ('Laboratorio de Materiales', 'Laboratorio de Materiales'), ('Autocontrol de Cocimiento', 'Autocontrol de Cocimiento'), ('Autocontrol de Fermentación', 'Autocontrol de Fermentación'), ('Autocontrol de Servicios', 'Autocontrol de Servicios'), ('Autocontrol de BTS', 'Autocontrol de BTS'), ('Autocontrol de PTA', 'Autocontrol de PTA'), ('Autocontrol de Filtros', 'Autocontrol de Filtros'), ('Autocontrol de Envasado', 'Autocontrol de Envasado'), ('Autocontrol de Sala de Válvulas', 'Autocontrol de Sala de Válvulas')], max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_calibracion', models.DateField(null=True)),
                ('fecha_proxima_calibracion', models.DateField(null=True)),
            ],
        ),
    ]
