# Generated by Django 5.1.7 on 2025-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('sector', models.CharField(choices=[('Autocontrol de Cocimiento', 'Autocontrol de Cocimiento'), ('Autocontrol de Fermentación', 'Autocontrol de Fermentación'), ('Autocontrol de Servicios', 'Autocontrol de Servicios'), ('Autocontrol de BTS', 'Autocontrol de BTS'), ('Autocontrol de PTA', 'Autocontrol de PTA')], max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
