# Generated by Django 5.1.7 on 2025-03-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_calibracion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_proxima_calibracion',
            field=models.DateField(null=True),
        ),
    ]
