# Generated by Django 5.1.7 on 2025-04-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_equipo_fecha_calibracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='sector',
            field=models.CharField(choices=[('Autocontrol de Cocimiento', 'Autocontrol de Cocimiento'), ('Autocontrol de Fermentación', 'Autocontrol de Fermentación'), ('Autocontrol de Servicios', 'Autocontrol de Servicios'), ('Autocontrol de BTS', 'Autocontrol de BTS'), ('Autocontrol de PTA', 'Autocontrol de PTA'), ('Autocontrol de Filtros', 'Autontrol de Filtros'), ('Autocontrol de Envasado', 'Autocontrol de Envasado'), ('Autocontrol de Sala de Válvulas', 'Autocontrol de Sala de Válvulas')], max_length=50),
        ),
    ]
